### PR TITLE
Prevent multiple reconnects from being scheduled simultaneously.

### PR DESCRIPTION
**Pull request by ufodone**
Proposed fix for #25

### CODE REVIEW

**Comment by ufodone** [comment]
@Cinntax Any chance you'd be able to have a look at this?

You previously mentioned maybe handing over maintenance of this project as you no longer have an alarm system that uses it at home so if you're still interested in that, let me know.

**Comment by Cinntax** [comment]
Hey @ufodone - thanks for checking in with me! Yes I'd definitely still be interested in transferring everything over.  I certainly don't mean to slow things up the way I have.

**Comment by ufodone** [comment]
Thanks, @Cinntax.  Let me know how you want to proceed with that.

**Comment by ufodone** [comment]
@Cinntax Hi again!  Sorry to bug you again but any thoughts of how to transfer the project?  And in the meantime, would you mind pushing a new version so I can get this fix into Home Assistant?  Thanks!

**Comment by Cinntax** [comment]
Hey @ufodone thanks for the reminder.  I just pushed version 4.5.  I'll make it a priority to ensuring the project is transferred over properly very soon!

**Comment by ufodone** [comment]
Thanks @Cinntax!

**Comment by Cinntax** [comment]
Hey @ufodone - I was looking into transferring ownership to you.  It looks like I can't do that since you have your own copy of it (the fork).  I think the easiest thing to do, as long as you have all your code merged in with mine... would be to just delete your fork, and let me know- and I can transfer it over to you.  That way you'd have all the PR history, issues, etc.

Also, do you have an account on pypi.org?  I can add you as an owner to the pyenvisalink package on there.

**Comment by ufodone** [comment]
Hi @Cinntax, I didn't have any unmerged changes in my fork so I've deleted it now.  I've also created an account on pypi.org with the same username as here.

**Comment by Cinntax** [comment]
Great @ufodone - I have submitted a request to transfer this over to you, and also invited you to the package on pypi.

I forgot to mention- you'll also want to sign up for an account on https://test.pypi.org as well so you can first deploy any new packages there.  I can make you an owner there as well as soon as you setup an account.

**Comment by ufodone** [comment]
@Cinntax : Okay, I've accepted the GitHub transfer and pypi invite and also created an account on test.pypi.org.  Almost there!

**Comment by Cinntax** [comment]
Great @ufodone - I also granted you ownership in test.pypi.org.  I think we're all set.  Thank you!!

**Comment by ufodone** [comment]
Thanks, @Cinntax.  Hopefully I'll be able to figure it out from here but I may need to bug you again at some point!

**Pull request merged**
