### PR TITLE
Additional enhancements to zone bypass feature (#14)

### PR DESCRIPTION
**Pull request by ufodone**
These changes are updates based on feedback I received trying to submit a PR to Home Assistant to expose the zone bypass feature there.  Two main changes:

* Added a public `toggle_zone_bypass` function to change the bypass state for a zone.
* The callback for a zone bypass status update now includes a map indicating which zones changed state.

### CODE REVIEW

**Comment by ufodone** [comment]
@Cinntax Would you mind having a peek at this when you get a chance?  I'm hoping to not leave the PR with Home Assistant hanging open for too long and it depends on these changes.   Thanks!

**Review by Cinntax — APPROVED** [review]
Looks good to me! I'll go ahead and get a new version published so you can bump the version on HA.

**Comment by dancinnamon-okta** [comment]
@ufodone - version 4.3 has been pushed to pypi with these changes in it.

**Comment by ufodone** [comment]
Thanks!

**Pull request merged**
